### PR TITLE
Merge with riscv-software-src/riscv-isa-sim repository

### PR DESCRIPTION
**Pull request by Bill94l**
Hi Charles,

I have updated the RISC-V ISA simulator. I will also submit a pull request for the changes in NaxRiscv and RVLS to ensure compatibility with the updated version of the SpinalHDL/riscv-isa-sim.

Thank you

### CODE REVIEW

**Comment by Dolu1990** [comment]
Hi,

Sure.
Let me know when you think it is good for merge / need review / hit a road block.

Thanks :)

**Comment by Bill94l** [comment]
Hi @Dolu1990 ,

Knowing that I want to choose the version of the update spike branch in both conflicts, what should I do to resolve these conflicts?

### processor.cc 
proc

### processor.h
proch

Thanks :D

**Comment by Dolu1990** [comment]
Hi,

So, basicaly those changes are related to the number of physical address bits that a given implementation has.
With NaxRiscv it was kinda assumned it was 32 bits. 
But i tried to make it right with VexiiRiscv.

Hmm
What's about we create a naxriscv branch for riscv-isa-sim ?
Idea being to decoupled the projects to take less risks (risks can waste a lot of time)
Same for RVLS

**Comment by Bill94l** [comment]
Hi,

> What's about we create a naxriscv branch for riscv-isa-sim ?

That's a great idea! However, in that case, I would need to create a new pull request for the NaxRiscv branch that you plan to create. Could you confirm if this is what you'd like me to do?

Thanks :D

**Comment by Dolu1990** [comment]
Hi ^^ 

Yup. naxriscv branch created, you can open the pr, then i will merge it on the spot :D

**Pull request closed without merging**
